### ISSUE TITLE
`sertop` ignores `COQPATH`

### ISSUE THREAD

**Issue by jhaag** [cpitclaudel/alectryon#1]
In our CI pipeline we set our `COQPATH` up so that it points to artifacts which we pull. Unfortunately, the only way that I've been able to get `sertop` to find these libraries is by adding something like the following into `sphinx/conf.py`:

```
serapi_args = []
coqpaths = os.environ.get("COQPATH", "").split(':')
for coqpath in coqpaths:
    if coqpath.endswith("foo/bar") or coqpath.endswith("baz/qux"):
        serapi_args.extend(["-R", coqpath + ","])

from alectryon.docutils import AlectryonTransform
AlectryonTransform.SERAPI_ARGS = serapi_args
```

It would be much better in terms of usability if `COQPATH` could be fed directly into `sertop` so that users don't need to manually parse their dependencies out and feed them in.

**Comment by cpitclaudel** [comment]
Fixed upstream.
