### ISSUE TITLE
Running with coqdoc frontend leaves coqdoc.css in current directory

### ISSUE THREAD

**Issue by palmskog** [cpitclaudel/alectryon#16]
Whenever I run Alectryon with the coqdoc frontend, e.g.,
```
alectryon.py --frontend coqdoc --webpage-style windowed \
   --output-directory docs/alectryon theories/Test.v
```
... I get `coqdoc.css` in the directory where I ran the command. Looking at coqdoc options, there doesn't seem to be one for avoiding css generation. Is this something that should be solved in Alectryon itself or reported upstream? Or even by the user running Alectryon?

**Comment by cpitclaudel** [comment]
Hmm, good point, yuck.  Probably upstream?  But the simplest in the meantime would be to run from a temporary directory; something like https://github.com/cpitclaudel/alectryon/pull/17 maybe? (I haven't had time to test it much yet)
