### ISSUE TITLE
Numbering lines within `.. coq::` blocks

### ISSUE THREAD

**Issue by jhaag** [cpitclaudel/alectryon#2]
In some of our documentation we dissect each line in a given snippet of Coq code individually. Oftentimes we refer to 'line 2' or 'line 7', but unfortunately Alectryon doesn't (seem to) have support for numbering the snippets in `.. coq::` blocks. It would be a nice quality-of-life improvement if line-numbering (similar to how it's done for regular [code blocks](https://www.sphinx-doc.org/en/1.7/markup/code.html#line-numbers)) was incorporated.

**Comment by cpitclaudel** [comment]
Actually, how about numbering sentences instead of lines?

```
.alectryon-io {
    counter-reset: sentences;
}

.alectryon-input {
    counter-increment: sentences;
}

.alectryon-io .alectryon-input:after,
.alectryon-io label.alectryon-input:after,
.alectryon-io label.alectryon-input:after,
.alectryon-io label.alectryon-input:hover:after {
    content: counter(sentences);
    /* Prettier display: */
    display: inline-block !important;
    border: thin solid #2e3436 !important;
    border-radius: 0;
    min-width: 1.35em;
    min-height: 1.35em;
    padding: 0.05em;
    text-align: center;
    background: #555753 !important;
    color: white;
    font-weight: 900;
    font-size: 75%;
    margin: 0 0 0 0.25em;
    vertical-align: middle;
    box-sizing: content-box;
}
```

Rendered:

![image](https://user-images.githubusercontent.com/8181630/127434569-e68c0146-de02-4581-927b-e2d4fba1c602.png)

**Comment by cpitclaudel** [comment]
Or for PL-minded folks, `content: counter(sentences, lower-greek);`:

![image](https://user-images.githubusercontent.com/8181630/127434949-8606a1cb-5b69-4f66-b12d-01be5f32cf4a.png)

**Comment by cpitclaudel** [comment]
(Of course, JS would also work for this),

It would also be nice to add a role in Alectryon for this; you'd write this:

```rst
.. coq::

  Check nat.
  Definition a : nat.
    apply Nat.add.
    exact 1.
    exact 1.
  Defined.

Pay particular attention to :coqref:`Check nat.` and :coqref:`exact 1 <2>`.
```

and it would render as this:

```
Check nat. [1]
Definition a : nat.
  apply Nat.add.
  exact 1.
  exact 1. [2]
Defined.

Pay particular attention to [1] and [2].
```

And it would check for you that the things you are referring to are actually in the code.

**Comment by jhaag** [comment]
These changes seem like they would certainly fit the bill! Thanks for looking into this in more earnest :~)

**Comment by cpitclaudel** [comment]
OK, I've implemented something which I think fits the bill; see the `:mref:` entry in https://github.com/cpitclaudel/alectryon#extra-roles-and-directives and the examples at https://github.com/cpitclaudel/alectryon/blob/master/recipes/references.rst .  The idea is that you refer to a sentence or a goal or a hypothesis by its contents, and Alectryon adds the corresponding markers in the right spots.

Here's the HTML:

![image](https://user-images.githubusercontent.com/8181630/128307861-44d2e820-9244-47fc-9d26-2ef6183ceda1.png)

And the PDF:

![image](https://user-images.githubusercontent.com/8181630/128307972-fa43bae3-be7b-4fc1-b5ab-9e306d6244c5.png)

**Comment by jhaag** [comment]
This looks great! I will test this out next week and get back to you regarding how well this fits our use-case :~)

**Comment by cpitclaudel** [comment]
Perfect, thanks

**Comment by jhaag** [comment]
While we're not going to update our existing documentation en masse with this new feature, it is indeed a good fit for the sort of documentation which I'm writing! I look forward to slowly integrating it more as we update and extend our documentation.

**Comment by cpitclaudel** [comment]
Perfect, excellent news (and yes, massive updates don't sound good!)  There may be a few tweaks to the syntax as we move forward, let me know if you run into corner cases or missing features!
