### ISSUE TITLE
Alectryon and GitHub Pages: no code highlighting and interactivity

### ISSUE THREAD

**Issue by anton-trunov** [cpitclaudel/alectryon#22]
First of all, thanks for the awesome tool!

I have an HTML version of a Coq document [lecture01.html](https://github.com/anton-trunov/csclub-coq-course-spring-2021/blob/master/lectures/lecture01.html) and also `alectryon.js` and `alectryon.css` in the same [directory](https://github.com/anton-trunov/csclub-coq-course-spring-2021/tree/master/lectures) but when GitHub Pages serves the page it seems that the interactivity and source code highlighting is lost (please see the rendered version here https://anton-trunov.github.io/csclub-coq-course-spring-2021/lectures/lecture01.html). It works locally, though.

Any idea how to fix it? Thanks in advance.

**Comment by cpitclaudel** [comment]
Check out the console output (right click, inspect):

```
GET https://anton-trunov.github.io/csclub-coq-course-spring-2021/lectures/docutils_basic.css
[HTTP/2 404 Not Found 15ms]

GET https://anton-trunov.github.io/csclub-coq-course-spring-2021/lectures/tango_subtle.css
[HTTP/2 404 Not Found 16ms]

GET https://anton-trunov.github.io/csclub-coq-course-spring-2021/lectures/tango_subtle.min.css
[HTTP/2 404 Not Found 17ms]
```

You're missing two more stylesheets that are used for syntax highlighting :)
(There should really be just one stylesheet for Pygments; it's a small improvement I need to make)

Are you using Alectryon for a class?! 🎉

**Comment by anton-trunov** [comment]
Oh, right. I had so many untracked files so I missed those. Sorry for the false alarm and thanks for your quick reply.

> Are you using Alectryon for a class?! 🎉

Yes! And I'm very much enjoying doing so :)

**Comment by cpitclaudel** [comment]
>  Yes! And I'm very much enjoying doing so :)

Woohoo!  Let me know if you run into any issues :)

**Comment by anton-trunov** [comment]
Absolutely! Thanks for your support :)
