### ISSUE TITLE
Alectryon coqdoc frontend bails on `(** printing ` directives

### ISSUE THREAD

**Issue by mattam82** [cpitclaudel/alectryon#40]
Just use a `.v` file with
```
(** printing Derive %\coqdockw{Derive}% *)
```
coqdoc uses it to configure itself, so it doesn't appear in the output, while alectryon understands it as a comment. This produces a `Coqdoc mismatch` assertion failure.

**Comment by cpitclaudel** [comment]
Ah, good catch, thanks! Do you have a list of these special assertions?

**Comment by mattam82** [comment]
I think there's only `(** printing` and `(** remove printing)` AFAIK

**Comment by cpitclaudel** [comment]
Should be fixed, I hope; can you check?

**Comment by mattam82** [comment]
Yep, it works fine!
Remaining problem: (* begin hide *) (* end hide *) are not recognized, that would be very helpful to me to understand it as (* . none *)

**Comment by mattam82** [comment]
![image](https://user-images.githubusercontent.com/98373/118661026-09896c80-b7ef-11eb-93e2-e34469c309ad.png)

**Comment by lthms** [comment]
On a related note, there is also `(* begin details *)` (`(* begin details : Summary of the section *)` is also valid) that has been added recently to `coqdoc`.

**Comment by cpitclaudel** [comment]
One problem with begin hide … end hide is that it doesn't respect sentences, so you can hide half of a command — Alectryon doesn't support that.

**Comment by mattam82** [comment]
Could we have a leniency option that doesn't support "inline" hide? I'm not using that feature afaik.

**Comment by cpitclaudel** [comment]
Sure.  I won't have time to implement it right away, but it should be easy.  Look in cli.py, though maybe some of that code should move to a separate coqdoc.py..
