### ISSUE TITLE
"Program Fixpoint" incorrectly translated

### ISSUE THREAD

**Issue by Casteran** [cpitclaudel/alectryon#45]
Alectryon translates a "Program Fixpoint"  definition into just "Fixpoint"

Require Import Coq.Program.Wf.
Require Import Coq.Arith.Arith.

  
Program Fixpoint f (n : nat ) {wf lt n} : nat :=
  match n  with
  | 0 => 0 
  | _ => f (n / 2)
  end.

**Comment by Zimmi48** [comment]
Great! We are looking forward to a new release.
