### ISSUE TITLE
alectryon.el expects a local Alectryon installation?

### ISSUE THREAD

**Issue by Zimmi48** [cpitclaudel/alectryon#55]
With a MELPA-installed `alectryon.el` and a globally installed `alectryon`, I got the following error:

```
Suspicious state from syntax checker alectryon: Flycheck checker alectryon returned 2, but its output contained no errors: /nix/store/66fbv9mmx1j4hrn9y06kcp73c3yb196r-python3-3.8.9/bin/python3: can't open file '/home/theo/.emacs.d/alectryon.py': [Errno 2] No such file or directory

Try installing a more recent version of alectryon, and please open a bug report if the issue persists in the latest release.  Thanks!
```

I'm suspecting that `alectryon.el` should also look for an `alectryon` binary in PATH.

**Comment by cpitclaudel** [comment]
Excellent point — having Alectryon in your path didn't use to be so common, but now we have a fancy PyPi package :star_struck: 

Will fix soon.
