### ISSUE TITLE
Syntax error in `alectryon/alectryon/transforms.py` using Python 3.7.5

### ISSUE THREAD

**Issue by jhaag** [cpitclaudel/alectryon#59]
In our CI we're using Python 3.7.5. I recently attempted to bump our version of alectryon but immediately ran into a syntax error within [this line](https://github.com/cpitclaudel/alectryon/blob/master/alectryon/transforms.py#L263). In particular, the use of the single-starred expression to create a variable length tuple is apparently not supported as it is currently written (i.e. `return obj.conclusion, *obj.hypotheses`).

I believe that if you change this line to `return (obj.conclusion, *obj.hypotheses)` then the code will continue working for the versions you test but it will _also_ work with Python 3.7.5

**Comment by cpitclaudel** [comment]
Ah, yes, thanks!  Will push a fix, I have a local patch :)

**Comment by cpitclaudel** [comment]
OK, closed by f3284f7 I think.

**Comment by jhaag** [comment]
Yep, I just confirmed that this works locally.

**Comment by cpitclaudel** [comment]
Thanks!

**Comment by cpitclaudel** [comment]
(Sorry btw, I should have rebased the commit to credit the issue report)

**Comment by jhaag** [comment]
Haha, I appreciate your thoughtfulness but I'm much more invested in functionality rather than attribution ;~)
