### ISSUE TITLE
[wish] :mquote:`nice <.s(foo).msg{*ugly*}>`

### ISSUE THREAD

**Issue by gares** [cpitclaudel/alectryon#63]
Sometimes I want to assert a message talk about the variable `X34` without quoting the entire message, eg. "coq complains variable x is illtyped"

**Comment by cpitclaudel** [comment]
Not sure I understand; can you give me an example of how the usage would look?

**Comment by gares** [comment]
maybe mquote is a misnaming and I want a massert. In the elpi tactic titorial there are many mquote:: , but if I want to mention a part of the message inline I have to quote it all, which is too much. So Id like to assert a message really contains what I think, but show only a little fragment of it in rhe middle of some text explaining it.

**Comment by cpitclaudel** [comment]
OK, then I got it right.  I have an implementation, will push soon :)

**Comment by cpitclaudel** [comment]
Done, check out the docs in the readme and in recipes/references.rst
