### ISSUE TITLE
Install path for manual installation

### ISSUE THREAD

**Issue by jjhugues** [cpitclaudel/alectryon#68]
(again related to my testing of #66)

On macOS, `python3 setup.py install` installs alectryon files in two directories: `alectryon-1.3.1-py3.9.egg alectryon-1.3.1.dist-info`. However, the pip package installs elements in `alectryon` and sphinx expects extensions there as well.

Is this the intended behavior? I had to to a symbolic link to test the current dev version

**Comment by cpitclaudel** [comment]
No idea, but it's standard behavior AFAIK? Alectryon's setup.py is basically empty (`from setuptools import setup; setup()`).
To install a local package I think you're supposed to use `pip install .`.

**Comment by jjhugues** [comment]
Right, `pip install .` installs in the correct directory. I wonder if you want to add this to the README

**Comment by cpitclaudel** [comment]
Done, thanks.
