### ISSUE TITLE
alectryon.el should assign a default value to flyspell-prog-text-faces

### ISSUE THREAD

**Issue by dunnl** [cpitclaudel/alectryon#88]
I think `(defvar flyspell-prog-text-faces)` [here](https://github.com/cpitclaudel/alectryon/blob/739b46da22d272e748f60f3efcd2989d696fba71/etc/elisp/alectryon.el#L406) should be changed to `(defvar flyspell-prog-text-faces nil)` or something to give the variable a default value. Because if `flyspell` isn't loaded, the former version leaves the variable void which causes `alectryon-mode` to fail with the following message when opening any Vernacular file, since it tries to manipulate a void variable. 
```
Debugger entered--Lisp error: (void-variable flyspell-prog-text-faces)
  alectryon-mode()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook proof-mode-hook coq-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook proof-mode-hook coq-mode-hook))
  run-mode-hooks(coq-mode-hook)
  coq-mode()
...snip...
  funcall-interactively(find-file "~/FermatsLastTheorem.v" t)
  call-interactively(find-file nil nil)
  command-execute(find-file)
```
Or should `flyspell` be loaded, but it looks like the intention here is to avoid needlessly loading it. I tested this on a fresh Emacs 28.1 with only Alectryon and Proof General installed from MELPA, and `(setq debug-on-error t)`.

**Comment by cpitclaudel** [comment]
Thanks for the great report.  I just pushed a tentative fix, could you give it a try?

**Comment by dunnl** [comment]
It works. Thanks.

**Comment by cpitclaudel** [comment]
Beautiful, thanks again for the report!
