### ISSUE TITLE
Nice quotes in TeX output

### ISSUE THREAD

**Issue by s5bug** [cpitclaudel/alectryon#95]
Perhaps this question belongs somewhere else, but searching for `rst quote tex` and similar queries came up short:

I have quoted phrases in my `.v`:

![image](https://github.com/cpitclaudel/alectryon/assets/7751296/d5986c2e-6e43-4b04-8fb3-5d593726caaa)

And these quotes always produce right-quotes:

![image](https://github.com/cpitclaudel/alectryon/assets/7751296/1564573b-984f-494c-b87b-7bf9733601e4)

when I would like them to produce quote-pairs:

![image](https://github.com/cpitclaudel/alectryon/assets/7751296/9c1a2311-17e1-43ae-a145-71a5725a8799)

The rules that build my `.tex` and `.pdf` are the following:
```make
$(RSTV_TEXES): %.v.tex: %.v $(patsubst %.dot,%.dot.tex,$(wildcard *.dot))
	alectryon --frontend coq+rst --backend latex --latex-dialect xelatex $< --output $@

$(RSTV_PDFS): %.pdf: %.v.tex
	latexmk -xelatex $^ -jobname=$* -interaction=nonstopmode
```
and I have a `docutils.conf` like so:
```
[xetex writer]
documentclass: scrartcl
latex-preamble:
  \usepackage{amsfonts}
  \usepackage{amssymb}
  \usepackage{tikz}
  \usetikzlibrary{shapes.geometric}
```

Any suggestions on how to fix this / where to move this issue to are very much appreciated 🙇

**Comment by cpitclaudel** [comment]
I believe you want "smart quotes": https://docutils.sourceforge.io/docs/user/smartquotes.html ; does that work?

**Comment by s5bug** [comment]
Yippee thank you!

![image](https://github.com/cpitclaudel/alectryon/assets/7751296/717a00c1-7be1-46fa-8019-34d59dd8f079)

**Comment by cpitclaudel** [comment]
Woot!  Thanks for the update.  Please do send me a link if you put your document online, so I can put it in the gallery :)

**Comment by s5bug** [comment]
As much as I'd love to, I don't think my professor would be too fond of me publicly sharing homework answers 😅
